version: "3.7"
services:
    web:
      image: sidsid14/docsgo:latest
      ports:
            - 80:80
      depends_on:
            - db    

    db:
      image: mysql
      volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
      environment:
            MYSQL_DATABASE: docsgo
            MYSQL_USER: user
            MYSQL_PASSWORD: docsgo@123
            MYSQL_ROOT_PASSWORD: docsgo@123 
      ports:
            - 3306:3306

    phpmyadmin:
            image: phpmyadmin/phpmyadmin
            depends_on:
                  - db   
            ports:
                  - 8000:80
            environment:
                  MYSQL_USER: user
                  MYSQL_PASSWORD: docsgo@123
                  MYSQL_ROOT_PASSWORD: docsgo@123 
volumes:
    persistent:
